name: Push to Branch Workflow

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  push-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push
        run: |
          git push origin HEAD:${{ github.ref }}
